# swagger.yml
# navigate to localhost:xxxx/api/ui to view API documentation

# title: Title included in the Connexion-generated UI system
# description: Description of what the API provides or is about
# version: Version value for the API
openapi: 3.0.0
info:
  title: "QueueTime Flask REST API"
  description: "QueueTime API for finding wait times of various points of interests at McMaster University"
  version: "1.0.0"

components:
  securitySchemes:
    jwt:
      type: http
      scheme: bearer
      bearerFormat: JWT
      x-bearerInfoFunc: app.common.decode_token

# # By providing "/api" as the value of url, you’ll be able to access all of your API paths relative to http://localhost:xxxx/api.
servers:
  - url: "/api"

components:
  # Security scheme to require a Bearer token
  securitySchemes:
    jwt:
      type: http
      scheme: bearer
      bearerFormat: JWT
      x-bearerInfoFunc: app.auth.validate_token

# /endpoint_name: The relative URL of your API endpoint
# get: The HTTP method that this URL endpoint will respond to
# operationId: The Python function that’ll respond to the request
# tags: The tags assigned to this endpoint, which allow you to group the operations in the UI
# summary: The UI display text for this endpoint
# responses: The status codes that the endpoint responds with
paths:
  /health:
    get:
      x-openapi-router-controller: app.health
      operationId: get_server_health
      responses:
        "200":
          description: "All good"
