name: Lint

on: [push]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: psf/black@stable
        with:
          options: "--check --verbose"
          src: "."
          version: "~= 22.0"

  typecheck:
    runs-on: ubuntu-latest
<<<<<<< HEAD
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"
      # Setup python environment
      - name: Install mypy dependency
        run: |
          python -m pip install --upgrade pip
          pip install mypy
      - name: Run mypy
        run: mypy app/ manage.py utils.py
=======
    - name: Set up Python 3.8
      uses: actions/setup-python@v4
          with:
            python-version: "3.8"
    # Setup python environment
    - name: Install mypy dependency
      run: |
        python -m pip install --upgrade pip
        pip install mypy
    - name: Run mypy
      run: mypy app/ manage.py utils.py
>>>>>>> Add mypy to lint workflow
