name: Notify on Discord

on:
  pull_request:
    types: [review_requested]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send notification to Discord
        uses: Ilshidur/action-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_USERNAME: "Notification Bot"
        with:
          args: "Hey, ${{ github.event.sender.name }} has requested a review from @{{ github.event.requested_reviewer.name }} on PR #{{ github.event.pull_request.number }}: ${{ github.event.pull_request.title }}"
