name: Notify on Discord

on:
  pull_request:
    types: [review_requested]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send notification to Discord
        uses: Ilshidur/action-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_USERNAME: "Notification Bot"
        with:
          args: "Hey, {{ EVENT_PAYLOAD.sender.name }} has requested a review from @{{ EVENT_PAYLOAD.requested_reviewer.name }} on PR #{{ EVENT_PAYLOAD.pull_request.number }}: ${{ EVENT_PAYLOAD.pull_request.title }}"
