name: Run unit tests
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"
      # Setup python environment
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: "temurin"
      - name: Setup firebase tools
        uses: w9jds/setup-firebase@main
        with:
          tools-version: 11.22.0
          gcp_sa_key: ${{ secrets.GCP_SA_KEY }}
      - name: Run unit tests in firebase emulator
        run: firebase emulators:exec --only firestore,auth --project qtime-bd47e 'python3 -m unittest discover -s ./test'
        env:
          SERVICE_KEY_PATH: "/opt/gcp_key.json"
