name: Run unit tests
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"
      # Setup python environment
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run tests in context of firebase emulator
        uses: w9jds/firebase-action@master
        with:
          args: "emulators:exec --only firestore,auth --project qtime-bd47e 'python -m unittest discover -s ./test'"
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
      # - name: Run unit tests
      #   run: python -m unittest discover -s ./test
